// <auto-generated />
namespace KryckoBlogSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedreferencetocommentsbyuserinUsersORM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedreferencetocommentsbyuserinUsersORM));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241049172_Added reference to comments by user in UsersORM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
